# Generated by Django 5.1.1 on 2024-12-01 21:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('type', models.CharField(default='comment', max_length=20)),
                ('username', models.CharField(max_length=32)),
                ('comment', models.TextField()),
                ('contentType', models.CharField(default='text/markdown', max_length=32)),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('type', models.CharField(default='like', max_length=255)),
                ('username', models.CharField(default='1', max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('object', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('type', models.CharField(default='likes', max_length=20)),
                ('page', models.URLField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.IntegerField(default=1)),
                ('size', models.IntegerField(default=50)),
                ('count', models.IntegerField(default=0)),
                ('src', models.ManyToManyField(related_name='like_collections', to='posts.like')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='likes_collection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='posts.likes'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('page', models.URLField()),
                ('description', models.CharField(max_length=200)),
                ('contentType', models.CharField(choices=[('text/markdown', 'Markdown'), ('text/plain', 'Plain Text'), ('application/base64', 'Base64 Image'), ('image/png;base64', 'PNG Image'), ('image/jpeg;base64', 'JPEG Image')], max_length=100)),
                ('content', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends'), ('UNLISTED', 'Unlisted'), ('DELETED', 'Deleted')], max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('likes_collection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts.likes')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.post'),
        ),
        migrations.CreateModel(
            name='githubPostIds',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post'),
        ),
    ]
